### ISSUE TITLE
How to use the visual Ant-maze environment.

### ISSUE THREAD

**Issue by RajGhugare19** [seohongpark/HIQL#1]
Hello folks -- I want to use the visual ant-maze environment that you describe in your paper. But after going through your code briefly, I am unable to spot where you have defined the visual ant-maze env. Could you point me towards the right place?

Thank you!

**Comment by seohongpark** [comment]
Hi Raj, thank you for your interest in our work.

Since we added Visual AntMaze and Roboverse results to the paper after cleaning up the code, the current codebase does not contain the Visual AntMaze environment at the moment. Adding these environments is still on our to-do list, but in the meantime, I can send you the code and dataset in our development branch via email if you need it.

**Comment by RajGhugare19** [comment]
That'd be great!
Here is my email : rajghugare.vnit@gmail.com

**Comment by NagisaZj** [comment]
> Hi Raj, thank you for your interest in our work.
> 
> Since we added Visual AntMaze and Roboverse results to the paper after cleaning up the code, the current codebase does not contain the Visual AntMaze environment at the moment. Adding these environments is still on our to-do list, but in the meantime, I can send you the code and dataset in our development branch via email if you need it.

Hi there, can you also send the codes to me? Thanks. My email: jin-zhan20@mails.tsinghua.edu.cn

**Comment by RenMing-Huang** [comment]
> Hi Raj, thank you for your interest in our work.
> 
> Since we added Visual AntMaze and Roboverse results to the paper after cleaning up the code, the current codebase does not contain the Visual AntMaze environment at the moment. Adding these environments is still on our to-do list, but in the meantime, I can send you the code and dataset in our development branch via email if you need it.

Hi , could you please send the codes to me? Thanks. My email: renming.huang@icloud.com

**Comment by Bxliang868** [comment]
> Hi Raj, thank you for your interest in our work.
> 
> Since we added Visual AntMaze and Roboverse results to the paper after cleaning up the code, the current codebase does not contain the Visual AntMaze environment at the moment. Adding these environments is still on our to-do list, but in the meantime, I can send you the code and dataset in our development branch via email if you need it.

Hi , could you please send the codes to me? Thanks. My email: bxliang@tongji.edu.cn

**Comment by chwoong** [comment]
> Hi Raj, thank you for your interest in our work.
> 
> Since we added Visual AntMaze and Roboverse results to the paper after cleaning up the code, the current codebase does not contain the Visual AntMaze environment at the moment. Adding these environments is still on our to-do list, but in the meantime, I can send you the code and dataset in our development branch via email if you need it.

Hi, could you please send the codes to me? Thanks. My email: [chw0501@snu.ac.kr](mailto:chw0501@snu.ac.rk)

**Comment by jlwwbo** [comment]
> Hi Raj, thank you for your interest in our work.
> 
> Since we added Visual AntMaze and Roboverse results to the paper after cleaning up the code, the current codebase does not contain the Visual AntMaze environment at the moment. Adding these environments is still on our to-do list, but in the meantime, I can send you the code and dataset in our development branch via email if you need it.

Hi, could you please send the codes to me? Thanks. My email: [jwb21@mails.tsinghua.edu.cn](mailto:jwb21@mails.tsinghua.edu.cn)

**Comment by zhyaoch** [comment]
Hi, could you please send the codes to me? Thanks. My email: zhangyaocheng23@mails.ucas.ac.cn

**Comment by zhyaoch** [comment]
> Hi Raj, thank you for your interest in our work.
> 
> Since we added Visual AntMaze and Roboverse results to the paper after cleaning up the code, the current codebase does not contain the Visual AntMaze environment at the moment. Adding these environments is still on our to-do list, but in the meantime, I can send you the code and dataset in our development branch via email if you need it.

Hi, could you please send the codes to me? Thanks. My email: zhangyaocheng23@mails.ucas.ac.cn

**Comment by seohongpark** [comment]
We have released the "official" version of Visual AntMaze in the [OGBench](https://github.com/seohongpark/ogbench) repository. This new version is slightly different from HIQL's Visual AntMaze because the new task doesn't provide proprioceptive information, but we found that they have similar levels of difficulty. We highly recommend using the new, publicly available Visual AntMaze environment along with the benchmarking results from the OGBench paper. In case you wish to reproduce the *exact* results from the HIQL paper based on the old version of Visual AntMaze, please feel free to email me.
